namespace FTikNib.Filtering

open FTikNib.Core

type FilterReason =
  | EmptyName = 0
  | InvalidAddress = 1
  | ZeroSize = 2
  | MissingSection = 3
  | NonCodeSection = 4
  | DynamicLinkageFunction = 5
  | RuntimeFunction = 6
  | ImportStub = 7
  | CompilerGeneratedFunction = 8
  | AutoGeneratedName = 9
  | DuplicateAddress = 10
  | DuplicateFunctionId = 11

type FunctionFilterOptions = {
  RemoveZeroSize: bool
  RequireKnownSection: bool
  RequireCodeSection: bool
  RemoveDynamicLinkageFunctions: bool
  RemoveRuntimeFunctions: bool
  RemoveImportStubs: bool
  RemoveCompilerGeneratedFunctions: bool
  RemoveAutoGeneratedNames: bool
}

type ExcludedFunction = {
  Function: FunctionInfo
  Reasons: FilterReason list
}

type FunctionFilterResult = {
  Included: FunctionInfo list
  Excluded: ExcludedFunction list
}

type FunctionFilteringResult = {
  Binary: BinaryInfo
  OriginalCount: int
  IncludedFunctions: FunctionInfo list
  ExcludedFunctions: ExcludedFunction list
}

module FunctionFilterOptions =

  let defaultOptions = {
    RemoveZeroSize = true
    RequireKnownSection = true
    RequireCodeSection = true
    RemoveDynamicLinkageFunctions = true
    RemoveRuntimeFunctions = true
    RemoveImportStubs = true
    RemoveCompilerGeneratedFunctions = false
    RemoveAutoGeneratedNames = true
  }